### ISSUE TITLE
Disabling chatwindows/tabs causes a game crash when you try open chat

### ISSUE THREAD

**Issue by baailey** [ebicep/ChatPlus#26]
kotlin.UninitializedPropertyAccessException: lateinit property chatWindow has not been initialized
	at com.ebicep.chatplus.features.chattabs.ChatTab.getChatWindow(ChatTab.java:140)
	at com.ebicep.chatplus.features.chattabs.ChatTabGetMessageAtEvent.<init>(ChatTabGetMessageAtEvent.java:132)
	at com.ebicep.chatplus.features.chattabs.ChatPositionTranslator.getMessageLineAt(ChatPositionTranslator.java:46)
	at com.ebicep.chatplus.features.chattabs.ChatPositionTranslator.getComponentStyleAt(ChatPositionTranslator.java:119)
	at com.ebicep.chatplus.features.chattabs.ChatTab.getComponentStyleAt(ChatTab.java:430)
	at net.minecraft.class_408.handler$zie000$chatplus$getComponentStyleAtRedirect(class_408.java:1335)
	at net.minecraft.class_408.method_44052(class_408.java)
	at net.minecraft.class_408.method_25394(class_408.java:211)
	at net.minecraft.class_437.method_47413(class_437.java:117)
	at net.minecraft.class_757.mixinextras$bridge$method_47413$258(class_757.java)
	at net.minecraft.class_757.wrapOperation$bjh000$fabric-screen-api-v1$onRenderScreen(class_757.java:3086)
	at net.minecraft.class_757.method_3192(class_757.java:913)
	at net.minecraft.class_310.method_1523(class_310.java:1285)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

**Comment by ebicep** [comment]
Fixed in v2.0.1 - See changelog for more info
