### ISSUE TITLE
Crashing After entering the command /chatplus

### ISSUE THREAD

**Issue by ZloyMels** [ebicep/ChatPlus#30]
Installed the mod. I decided to look through the mod at the list of displayed available mods, and decided to find the settings of the chat plus mod. They are not there (I went to the site where the mod was published and saw that there was a command there.Entered the command /chatplus and me crashed the game

**Comment by ZloyMels** [comment]
Pojavlauncher 
1.20.4
Fabric

**Comment by ebicep** [comment]
Unable to reproduce.
1. Do you have a crash log?
2. Is this still a problem if you only use ChatPlus?

**Comment by MiguelSampaioBarth** [comment]
the error is:
The game crashed whilst unexpected error
Error: java.lang.NoClassDefFoundError: me/shedaniel/clothconfig2/api/ConfigBuilder

and the log is:

java.lang.NoClassDefFoundError: me/shedaniel/clothconfig2/api/ConfigBuilder
	at com.ebicep.chatplus.config.fabric.ConfigScreenImpl.getConfigScreen(ConfigScreenImpl.kt:37)
	at com.ebicep.chatplus.config.ConfigScreen.getConfigScreen(ConfigScreen.java)
	at com.ebicep.chatplus.config.ConfigScreen.getConfigScreen$default(ConfigScreen.java:25)
	at com.ebicep.chatplus.config.ConfigScreen.openConfigScreen(ConfigScreen.java:19)
	at com.ebicep.chatplus.config.ConfigScreen.handleOpenScreen(ConfigScreen.java:14)
	at com.ebicep.chatplus.events.Events._init_$lambda$0(Events.java:41)
	at dev.architectury.event.fabric.EventHandlerImpl.lambda$registerClient$3(EventHandlerImpl.java:52)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:43)
	at net.minecraft.class_310.handler$zkc000$fabric-lifecycle-events-v1$onEndTick(class_310.java:5183)
	at net.minecraft.class_310.method_1574(class_310.java:2012)
	at net.minecraft.class_310.method_1523(class_310.java:1246)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassNotFoundException: me.shedaniel.clothconfig2.api.ConfigBuilder
	... 16 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.ebicep.chatplus.config.fabric.ConfigScreenImpl.getConfigScreen(ConfigScreenImpl.kt:37)
	at com.ebicep.chatplus.config.ConfigScreen.getConfigScreen(ConfigScreen.java)
	at com.ebicep.chatplus.config.ConfigScreen.getConfigScreen$default(ConfigScreen.java:25)
	at com.ebicep.chatplus.config.ConfigScreen.openConfigScreen(ConfigScreen.java:19)
	at com.ebicep.chatplus.config.ConfigScreen.handleOpenScreen(ConfigScreen.java:14)
	at com.ebicep.chatplus.events.Events._init_$lambda$0(Events.java:41)
	at dev.architectury.event.fabric.EventHandlerImpl.lambda$registerClient$3(EventHandlerImpl.java:52)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:43)
	at net.minecraft.class_310.handler$zkc000$fabric-lifecycle-events-v1$onEndTick(class_310.java:5183)

-- Uptime --
Details:
	JVM uptime: 127.896s
	Wall uptime: 116.653s
	High-res time: 114.007s
	Client ticks: 2081 ticks / 104.050s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2501)
	at net.minecraft.class_310.method_54580(class_310.java:949)
	at net.minecraft.class_310.method_1514(class_310.java:905)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 13 total; [class_746['M1ke_27735'/379539, l='ClientLevel', x=-68.50, y=132.00, z=0.50], class_745['§8[NPC] 9891'/1, l='ClientLevel', x=-62.00, y=132.00, z=4.00], class_745['§8[NPC] 6621'/25, l='ClientLevel', x=-48.50, y=129.00, z=14.50], class_745['§8[NPC] 2572'/56, l='ClientLevel', x=-52.50, y=128.00, z=0.50], class_745['§8[NPC] 3776'/53, l='ClientLevel', x=-68.50, y=131.00, z=-7.50], class_745['§8[NPC] 5400'/5, l='ClientLevel', x=-48.50, y=129.00, z=-13.50], class_745['§8[NPC] 5001'/9, l='ClientLevel', x=-46.50, y=129.00, z=-9.50], class_745['§8[NPC] 161'/17, l='ClientLevel', x=-45.50, y=129.00, z=-5.50], class_745['§8[NPC] 6092'/21, l='ClientLevel', x=-44.50, y=129.00, z=-1.50], class_745['§8[NPC] 8558'/13, l='ClientLevel', x=-45.50, y=129.00, z=6.50], class_745['§8[NPC] 6751'/29, l='ClientLevel', x=-46.50, y=129.00, z=10.50], class_745['§8[NPC] 9441'/33, l='ClientLevel', x=-44.50, y=129.00, z=2.50], class_745['§8[NPC] 531'/37, l='ClientLevel', x=-59.50, y=128.00, z=-27.50]]
	Chunk stats: 18225, 441
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,64,0), Section: (at 0,0,0 in 0,4,0; chunk contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 42753 game time, 4284 day time
	Server brand: Fakepixel
	Server type: Non-integrated multiplayer server
	Tracked entity count: 89

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, betterfpsdist, chatplus, dynamic_fps, entityculling, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, fpsdisplay, fpsreducer, iris, lithium, modernfix, modmenu, placeholder-api, smoothchunk, smoothgui, sodium, wi_zoom, file/Fancy Crops v1.0 f5-34.zip, file/JermsyBoy's Better Leaves V3.1-1.21.zip, file/Super RPG Font.zip, file/ultimacraft-pbr-v-1-7.zip

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 70365240 bytes (67 MiB) / 815792128 bytes (778 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 4800H with Radeon Graphics         
	Identifier: AuthenticAMD Family 23 Model 96 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 2.89
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: AMD Radeon(TM) Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc.
	Graphics card #0 VRAM (MiB): 512.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 27.20.1022.3003
	Graphics card #1 name: NVIDIA GeForce GTX 1650
	Graphics card #1 vendor: NVIDIA
	Graphics card #1 VRAM (MiB): 4096.00
	Graphics card #1 deviceId: VideoController2
	Graphics card #1 versionInfo: 32.0.15.5612
	Memory slot #0 capacity (MiB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Virtual memory max (MiB): 19709.32
	Virtual memory used (MiB): 12167.81
	Swap memory total (MiB): 3968.00
	Swap memory used (MiB): 47.51
	Space in storage for jna.tmpdir (MiB): available: 103261.01, total: 244197.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 103261.01, total: 244197.00
	Space in storage for io.netty.native.workdir (MiB): available: 103261.01, total: 244197.00
	Space in storage for java.io.tmpdir (MiB): available: 103261.01, total: 244197.00
	Space in storage for workdir (MiB): available: 103261.01, total: 244197.00
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Fabric Mods: 
		architectury: Architectury 13.0.6
		betterfpsdist: Better FPS distance Mod 1.21-5.1
		chatplus: ChatPlus 2.0.1
			com_alphacephei_vosk: vosk 0.3.45
		cupboard: cupboard 1.21-2.7
		dynamic_fps: Dynamic FPS 3.6.3
			net_lostluma_battery: battery 1.1.0
		entityculling: EntityCulling 1.7.0
		fabric-api: Fabric API 0.102.0+1.21
			fabric-api-base: Fabric API Base 0.4.42+6573ed8cd1
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.68+b5597344d1
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.29+5bd9f1bcd1
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a7d1
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8cd1
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a7d1
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8cd1
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366fd1
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd9d1
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b3d1
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.16+b5597344d1
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.19+7f945d5bd1
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.5.0+c5e2b5c6d1
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a7d1
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.27+6a6dfa19d1
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.16+16c4ae25d1
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b99d1
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b99d1
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.12+ba9dae06d1
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd9d1
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc921d1
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.4+78017270d1
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a7d1
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b3d1
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.12+6c1df360d1
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.14+3f89f5a5d1
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.2+3f89f5a5d1
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8cd1
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6bd1
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.2+60c3209bd1
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.0+a551f7a4d1
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8cd1
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.12+65089712d1
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.1.2+60c3209bd1
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49cd1
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49cd1
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b3d1
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2ed1
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+b5597344d1
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b3d1
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd0d1
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b1d1
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.0+56599129d1
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.24+b5597344d1
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.86+b5597344d1
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8cd1
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.16+3dccd343d1
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.0+176f9036d1
		fabric-language-kotlin: Fabric Language Kotlin 1.12.1+kotlin.2.0.20
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.20
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.20
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.25.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.1
			org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.5.3
			org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.5.3
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.1
		fabricloader: Fabric Loader 0.16.5
			mixinextras: MixinExtras 0.4.1
		fpsdisplay: FPS-Display 4.2.1+1.21.1
		fpsreducer: FPS Reducer 1.21-2.9
		iris: Iris 1.8.0-beta.3+mc1.21.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		java: OpenJDK 64-Bit Server VM 21
		lithium: Lithium 0.13.0
		minecraft: Minecraft 1.21
		modelfix: Model Gap Fix 1.21-1.6
		modernfix: ModernFix 5.19.1+mc1.21
		modmenu: Mod Menu 11.0.2
		placeholder-api: Placeholder API 2.4.1+1.21
		smoothchunk: Smooth chunk save Mod 1.21-3.6
		smoothgui: SmoothGui 0.1.1
		sodium: Sodium 0.6.0-beta.1+mc1.21
		wi_zoom: WI Zoom 1.5-MC1.21
	Loaded Shaderpack: photon_v1.0a.zip
		Profile: high (+0 options changed by user)
	Launched Version: fabric-loader-0.16.5-1.21
	Launcher name: minecraft-launcher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: NVIDIA GeForce GTX 1650/PCIe/SSE2 GL version 3.2.0 NVIDIA 556.12, NVIDIA Corporation
	Window size: 1024x768
	GFLW Platform: win32
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Render Distance: 12/12 chunks
	Resource Packs: vanilla, fabric, betterfpsdist (incompatible), chatplus, dynamic_fps, entityculling, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, fpsdisplay, fpsreducer, iris, lithium, modernfix (incompatible), modmenu, placeholder-api, smoothchunk (incompatible), smoothgui, sodium, wi_zoom, file/Fancy Crops v1.0 f5-34.zip, file/JermsyBoy's Better Leaves V3.1-1.21.zip, file/Super RPG Font.zip (incompatible), file/ultimacraft-pbr-v-1-7.zip
	Current Language: en_us
	Locale: en_US
	System encoding: Cp1252
	File encoding: UTF-8
	CPU: 16x AMD Ryzen 7 4800H with Radeon Graphics 
![image](https://github.com/user-attachments/assets/8ce8ac77-8bc3-4863-96c3-9b8db59065c7)

**Comment by ebicep** [comment]
Do you have cloth config as a mod?

**Comment by MiguelSampaioBarth** [comment]
no, i gather many mods along with chatplus, but no cloth

**Comment by ebicep** [comment]
Cloth config is a dependency, you need it to view the config. Make sure you have the other dependencies installed too.

**Comment by ebicep** [comment]
Closing due to inactivity and I believe the problem is solved.
